# Generated by Django 5.1 on 2024-12-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_scalpdetect_scalpproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='scalpproduct',
            name='quantity',
        ),
    ]
